---
  elasticsearch:
    hosts:
      localhost:
        ansible_connection: ssh
        ansible_user: vagrant
        ansible_port: 2222
        ansible_private_key_file: .vagrant/machines/elastichost/virtualbox/private_key





